# Generated by Django 5.2.3 on 2025-06-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_candidate_vote_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voter',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
