# Generated by Django 5.2.3 on 2025-06-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_voter_is_active_voter_is_staff_voter_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='role',
            field=models.CharField(choices=[('voter', 'Voter'), ('admin', 'Admin')], default='voter', max_length=10),
        ),
    ]
