# Generated by Django 5.2.3 on 2025-06-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_voter_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Voter')], default=2),
        ),
    ]
