# Generated by Django 5.2.3 on 2025-06-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_voter_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Voter'), (3, 'Staff')], default=2),
        ),
    ]
