# Generated by Django 5.2.3 on 2025-06-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_voter_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='otp_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
