# Generated by Django 5.2.3 on 2025-06-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_voter_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
