# Generated by Django 5.2.3 on 2025-06-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_poll_end_time_poll_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='new_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
