# Generated by Django 5.2.3 on 2025-06-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_voter_new_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='phone_change_otp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
