# Generated by Django 5.2.3 on 2025-06-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_voter_phone_change_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
