# Generated by Django 5.2.3 on 2025-06-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_candidate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
