# Generated by Django 5.2.3 on 2025-06-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_poll_end_date_poll_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
