# Generated by Django 5.2.3 on 2025-06-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_poll_end_time_alter_poll_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('poll', 'name')},
        ),
    ]
