# Generated by Django 5.2.3 on 2025-06-26 08:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_candidate_name_alter_candidate_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, message='Имя должно содержать минимум 2 символа'), django.core.validators.RegexValidator("^[А-Яа-яA-Za-zёЁ\\-\\' ]+$", message='Имя должно содержать только буквы')]),
        ),
        migrations.AlterField(
            model_name='voter',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, message='Фамилия должна содержать минимум 2 символа'), django.core.validators.RegexValidator("^[А-Яа-яA-Za-zёЁ\\-\\' ]+$", message='Фамилия должна содержать только буквы')]),
        ),
    ]
